### ISSUE TITLE
return status 

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-flow#12]
```
    entry:
      color: green
      label: b
      value: x
      shape: circle
```

make sure the value is interpreted as array, you can use the 
Parameter class from cloudmesh to convert it in an array. 
But this is important as this needs to be interpreted by The viz component. Alternatively you could simply convert this as a string and pass along to the gui as string, so there are multiple ways this could be done, but agree upon what you expect

```
    entry:
      color: green
      label: b
      value: x, y
      shape: circle
```
So one way is (pseudocode)

vars = Parameter.expand(value)
for var in vars:
   value[var] = get value for var (database, or eval(var)

now you have an array and you can convert it to a string

out = `, '.join(vars)

now you can use out in the vis and are able to print n values also
